# Compiler and flags
CXX      := g++
WARNINGS := -Wall -Wextra -Wshadow
# -MMD -MP emit .d files so edits to a header rebuild every dependent .o
CXXFLAGS := -g -std=c++17 $(WARNINGS) -Iinclude -MMD -MP

# Directories
SRCDIR  := src
INCDIR  := include
OBJDIR  := obj
BINDIR  := bin
TESTDIR := tests

# Grab all .cpp files under src/
SRCS := $(wildcard $(SRCDIR)/*.cpp)

# Turn "src/foo.cpp" into "obj/foo.o"
OBJS := $(patsubst $(SRCDIR)/%.cpp,$(OBJDIR)/%.o,$(SRCS))

# Everything the tests link against: the library plus the parsers, CLI helpers
# and printers. Only main is left out.
TEST_LIB_SRCS := $(SRCDIR)/bezier.cpp $(SRCDIR)/scalar-profile.cpp \
                 $(SRCDIR)/scalar-profiler.cpp $(SRCDIR)/motion-profiling.cpp \
                 $(SRCDIR)/motion-profiler.cpp $(SRCDIR)/ramsete.cpp \
                 $(SRCDIR)/file-parser.cpp $(SRCDIR)/cli-args.cpp \
                 $(SRCDIR)/mechanism-file.cpp $(SRCDIR)/printer.cpp \
                 $(SRCDIR)/velocity-profiler.cpp
TEST_LIB_OBJS := $(patsubst $(SRCDIR)/%.cpp,$(OBJDIR)/%.o,$(TEST_LIB_SRCS))

TEST_SRCS := $(wildcard $(TESTDIR)/*.cpp)
TEST_OBJS := $(patsubst $(TESTDIR)/%.cpp,$(OBJDIR)/tests/%.o,$(TEST_SRCS))

# Example programs live under examples/ and each build into their own binary.
EXAMPLEDIR := examples
EXAMPLE_EXE := $(BINDIR)/scalar-profile-demo
# The 1D example only needs the scalar core, not the Bezier/RAMSETE code.
EXAMPLE_LIB_OBJS := $(OBJDIR)/scalar-profile.o $(OBJDIR)/scalar-profiler.o

# Final executables
EXE      := $(BINDIR)/main
TEST_EXE := $(BINDIR)/tests

# Default target: make sure bins + objs exist, then build the exe
all: $(BINDIR) $(OBJDIR) $(EXE)

# Link step: link all .o files into bin/main
$(EXE): $(OBJS) | $(BINDIR)
	$(CXX) $^ -o $@

# Compile step: for each src/%.cpp -> obj/%.o
$(OBJDIR)/%.o: $(SRCDIR)/%.cpp | $(OBJDIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Test objects need the vendored doctest header on the include path.
$(OBJDIR)/tests/%.o: $(TESTDIR)/%.cpp | $(OBJDIR)/tests
	$(CXX) $(CXXFLAGS) -I$(TESTDIR)/vendor -c $< -o $@

$(TEST_EXE): $(TEST_LIB_OBJS) $(TEST_OBJS) | $(BINDIR)
	$(CXX) $^ -o $@

# Build and run the unit tests
.PHONY: test
test: $(BINDIR) $(OBJDIR) $(TEST_EXE)
	./$(TEST_EXE)

# Example objects compile like src objects but live under examples/.
$(OBJDIR)/examples/%.o: $(EXAMPLEDIR)/%.cpp | $(OBJDIR)/examples
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(EXAMPLE_EXE): $(EXAMPLE_LIB_OBJS) $(OBJDIR)/examples/scalar_profile_demo.o | $(BINDIR)
	$(CXX) $^ -o $@

# Build the example programs
.PHONY: example
example: $(BINDIR) $(OBJDIR) $(EXAMPLE_EXE)

# Create bin/, obj/, obj/tests/ and obj/examples/ if they don't exist
$(OBJDIR) $(BINDIR) $(OBJDIR)/tests $(OBJDIR)/examples:
	mkdir -p $@

# "make clean"
.PHONY: clean
clean:
	rm -rf $(OBJDIR) $(BINDIR)

# Mark "all" as phony so it always runs
.PHONY: all

# Header dependencies generated by -MMD
-include $(OBJS:.o=.d) $(TEST_OBJS:.o=.d) $(OBJDIR)/examples/scalar_profile_demo.d
