#include "doctest.h"
#include "printer.hpp"

#include <sstream>
#include <string>
#include <vector>

namespace {

const std::vector<ScalarSample> kSamples = {
    {0.0, 0.0, 0.0, 0.0},
    {0.0015, 0.3, 30.0, 0.01},
};

// Everything a 1D Rust module prints ahead of its samples.
const std::string kMotionSampleRust =
    "// Generated by vmplib.\n"
    "\n"
    "#[derive(Clone, Copy, Debug, PartialEq)]\n"
    "pub struct MotionSample {\n"
    "    /// s\n"
    "    pub time: f64,\n"
    "    /// units/s\n"
    "    pub velocity: f64,\n"
    "    /// units/s^2 that carry this sample to the next; 0 at the last\n"
    "    pub accel: f64,\n"
    "}\n"
    "\n"
    "#[rustfmt::skip]\n"
    "pub static SAMPLES: &[MotionSample] = &[\n";

} // namespace

TEST_CASE("1D samples print as three Desmos lists against time") {
    std::ostringstream out;
    Printer::printScalarSamplesDesmos(out, kSamples);
    CHECK(out.str() == "P = [(0.000000,0.000000),(0.010000,0.001500)]\n"
                       "V = [(0.000000,0.000000),(0.010000,0.300000)]\n"
                       "A = [(0.000000,0.000000),(0.010000,30.000000)]\n");
}

TEST_CASE("1D samples print as a C++ initialiser list") {
    std::ostringstream out;
    Printer::printScalarSamplesCpp(out, kSamples);
    CHECK(out.str() ==
          "S = {{0.000000, 0.000000, 0.000000},{0.001500, 0.300000, 30.000000}};\n");
}

TEST_CASE("velocity samples print as two Desmos lists against time") {
    const std::vector<VelocitySample> samples = {{0.0, 0.0, 0.0}, {8.0, 800.0, 0.01}};
    std::ostringstream out;
    Printer::printVelocitySamplesDesmos(out, samples);
    CHECK(out.str() == "V = [(0.000000,0.000000),(0.010000,8.000000)]\n"
                       "A = [(0.000000,0.000000),(0.010000,800.000000)]\n");
}

TEST_CASE("velocity samples print as a C++ initialiser list") {
    const std::vector<VelocitySample> samples = {{0.0, 0.0, 0.0}, {8.0, 800.0, 0.01}};
    std::ostringstream out;
    Printer::printVelocitySamplesCpp(out, samples);
    CHECK(out.str() == "S = {{0.000000, 0.000000},{8.000000, 800.000000}};\n");
}

TEST_CASE("1D samples print as a Rust slice, each carrying the accel into the next sample") {
    std::ostringstream out;
    Printer::printScalarSamplesRust(out, kSamples);
    CHECK(out.str() == kMotionSampleRust +
                           "    MotionSample { time: 0.0, velocity: 0.0, accel: 30.0 },\n"
                           "    MotionSample { time: 0.01, velocity: 0.3, accel: 0.0 },\n"
                           "];\n");
}

TEST_CASE("velocity samples print as the same Rust slice") {
    const std::vector<VelocitySample> samples = {{0.0, 0.0, 0.0}, {8.0, 800.0, 0.01}};
    std::ostringstream out;
    Printer::printVelocitySamplesRust(out, samples);
    CHECK(out.str() == kMotionSampleRust +
                           "    MotionSample { time: 0.0, velocity: 0.0, accel: 800.0 },\n"
                           "    MotionSample { time: 0.01, velocity: 8.0, accel: 0.0 },\n"
                           "];\n");
}

TEST_CASE("no samples print as an empty Rust slice") {
    std::ostringstream out;
    Printer::printScalarSamplesRust(out, {});
    CHECK(out.str() == kMotionSampleRust + "];\n");
}

TEST_CASE("Rust values keep full f64 precision and always read as floats") {
    const std::vector<VelocitySample> samples = {{0.1 + 0.2, 0.0, 0.0}, {-0.0, 1e-7, 0.01}};
    std::ostringstream out;
    Printer::printVelocitySamplesRust(out, samples);
    const std::string text = out.str();
    CHECK(text.find("    MotionSample { time: 0.0, velocity: 0.30000000000000004, accel: 1e-07 },\n") !=
          std::string::npos);
    CHECK(text.find("    MotionSample { time: 0.01, velocity: -0.0, accel: 0.0 },\n") !=
          std::string::npos);
}

TEST_CASE("drive samples print as a Rust slice") {
    const std::vector<DriveSample> samples = {
        {0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 3.0},
        {0.01, 0.03, 0.5, -0.045, 0.105, 0.0, 0.0},
    };
    std::ostringstream out;
    Printer::printDriveSamplesRust(out, samples);
    CHECK(out.str() ==
          "// Generated by vmplib.\n"
          "\n"
          "#[derive(Clone, Copy, Debug, PartialEq)]\n"
          "pub struct DriveSample {\n"
          "    /// s\n"
          "    pub time: f64,\n"
          "    /// m/s, at the centre of the robot\n"
          "    pub linear_velocity: f64,\n"
          "    /// rad/s, counterclockwise positive\n"
          "    pub angular_velocity: f64,\n"
          "    /// m/s\n"
          "    pub left_velocity: f64,\n"
          "    /// m/s\n"
          "    pub right_velocity: f64,\n"
          "    /// m/s^2 that carry the left side to the next sample; 0 at the last\n"
          "    pub left_accel: f64,\n"
          "    /// m/s^2 that carry the right side to the next sample; 0 at the last\n"
          "    pub right_accel: f64,\n"
          "}\n"
          "\n"
          "#[rustfmt::skip]\n"
          "pub static SAMPLES: &[DriveSample] = &[\n"
          "    DriveSample { time: 0.0, linear_velocity: 0.0, angular_velocity: 0.0, "
          "left_velocity: 0.0, right_velocity: 0.0, left_accel: 3.0, right_accel: 3.0 },\n"
          "    DriveSample { time: 0.01, linear_velocity: 0.03, angular_velocity: 0.5, "
          "left_velocity: -0.045, right_velocity: 0.105, left_accel: 0.0, right_accel: 0.0 },\n"
          "];\n");
}

TEST_CASE("drive samples can be written as a type the crate already defines") {
    const std::vector<DriveSample> samples = {{0.0, 0.5, 1.0, 0.35, 0.65, 2.0, -1.0}};
    std::ostringstream out;
    Printer::printDriveSamplesRust(out, samples, "crate::motion_profile::DriveSample");
    CHECK(out.str() ==
          "// Generated by vmplib.\n"
          "\n"
          "use crate::motion_profile::DriveSample;\n"
          "\n"
          "#[rustfmt::skip]\n"
          "pub static SAMPLES: &[DriveSample] = &[\n"
          "    DriveSample { time: 0.0, linear_velocity: 0.5, angular_velocity: 1.0, "
          "left_velocity: 0.35, right_velocity: 0.65, left_accel: 2.0, right_accel: -1.0 },\n"
          "];\n");
}

TEST_CASE("every 1D sample is written as the imported type's own name") {
    std::ostringstream out;
    Printer::printScalarSamplesRust(out, kSamples, "crate::profiles::Step");
    CHECK(out.str() == "// Generated by vmplib.\n"
                       "\n"
                       "use crate::profiles::Step;\n"
                       "\n"
                       "#[rustfmt::skip]\n"
                       "pub static SAMPLES: &[Step] = &[\n"
                       "    Step { time: 0.0, velocity: 0.0, accel: 30.0 },\n"
                       "    Step { time: 0.01, velocity: 0.3, accel: 0.0 },\n"
                       "];\n");
}

TEST_CASE("a type already in scope is used without importing it") {
    std::ostringstream out;
    Printer::printVelocitySamplesRust(out, {}, "Step");
    CHECK(out.str() == "// Generated by vmplib.\n"
                       "\n"
                       "#[rustfmt::skip]\n"
                       "pub static SAMPLES: &[Step] = &[\n"
                       "];\n");
}
