// printer.cpp
//
// The output boundary. Internal state is carried in double (see types.hpp);
// the Desmos and C++ formats narrow it to float here, on the way out, because
// that is the precision a Desmos plot or a C++ velocity controller consumes. The
// Rust format keeps the full double as an f64.
#include "printer.hpp"
#include <charconv>
#include <iomanip>
#include <ostream>

namespace {

constexpr const char* kRustHeader = "// Generated by vmplib.\n\n";

// value as the shortest f64 literal that Rust reads back to the same double.
// The shortest text can be a bare integer such as "30", which Rust would type as
// an integer, so that gets a ".0".
std::string rustFloat(double value) {
	char buf[32];
	const auto result = std::to_chars(buf, buf + sizeof buf, value);
	std::string text(buf, result.ptr);
	if (text.find_first_of(".e") == std::string::npos) {
		text += ".0";
	}
	return text;
}

// The Rust MotionSample module shared by both 1D sample types. Each sample
// carries the accel stored on the next one, which is (next velocity - this
// velocity) / dt.
template <typename Sample>
void printMotionSamplesRust(std::ostream& out, const std::vector<Sample>& samples) {
	out << kRustHeader
	    << "#[derive(Clone, Copy, Debug, PartialEq)]\n"
	       "pub struct MotionSample {\n"
	       "    /// s\n"
	       "    pub time: f64,\n"
	       "    /// units/s\n"
	       "    pub velocity: f64,\n"
	       "    /// units/s^2 that carry this sample to the next; 0 at the last\n"
	       "    pub accel: f64,\n"
	       "}\n"
	       "\n"
	       "pub static SAMPLES: &[MotionSample] = &[\n";
	for (size_t i = 0; i < samples.size(); ++i) {
		const double accel = i + 1 < samples.size() ? samples[i + 1].accel : 0.0;
		out << "    MotionSample { time: " << rustFloat(samples[i].time)
		    << ", velocity: " << rustFloat(samples[i].velocity)
		    << ", accel: " << rustFloat(accel) << " },\n";
	}
	out << "];\n";
}

// Prints label[(t, value),...] for one field of any sample carrying a time.
template <typename Sample>
void printAgainstTime(
	std::ostream& out,
	const char* label,
	const std::vector<Sample>& samples,
	double Sample::*field
) {
	out << label << "[";
	for (size_t i = 0; i < samples.size(); ++i) {
		if (i != 0) out << ",";
		out << "("
			<< std::fixed << std::setprecision(6)
			<< static_cast<float>(samples[i].time) << ","
			<< static_cast<float>(samples[i].*field)
			<< ")";
	}
	out << "]\n";
}

} // namespace

namespace Printer {

void printPoseVectorDesmos(
	std::ostream& out,
	const std::string& label,
	const std::vector<std::vector<Pose>>& poses
) {
	out << label << "[";
	for (size_t i = 0; i < poses.size(); ++i) {
		for (size_t j = 0; j < poses[i].size(); ++j) {
			out
				<< "("
				<< std::fixed << std::setprecision(6)
				<< static_cast<float>(poses[i][j].x) << ","
				<< static_cast<float>(poses[i][j].y)
				<< ")";
			if (i != poses.size() - 1 || j != poses[i].size() - 1) {
				out << ",";
			}
		}
	}
	out << "]\n";
}

void printVelocityVectorDesmos(
	std::ostream& out,
	const std::string& label,
	const std::vector<std::vector<VelocityLayout>>& vels,
	const std::string& whichField
) {
	out << label << "[";
	for (size_t i = 0; i < vels.size(); ++i) {
		for (size_t j = 0; j < vels[i].size(); ++j) {
			float value = static_cast<float>((whichField == "linear")
				? vels[i][j].linear
				: vels[i][j].angular);
			out
				<< "("
				<< std::fixed << std::setprecision(6)
				<< static_cast<float>(vels[i][j].time) << ","
				<< value
				<< ")";
			if (i != vels.size() - 1 || j != vels[i].size() - 1) {
				out << ",";
			}
		}
	}
	out << "]\n";
}

// prints P = {(x, y),(x, y),...}
void printPoseVectorCpp(
	std::ostream& out,
	const std::string& label,
	const std::vector<std::vector<Pose>>& poses
) {
	out << label << " {";

	bool first = true;
	for (const auto& row : poses) {
		for (const auto& p : row) {
			if (!first) out << ",";
			out << "("
				<< std::fixed << std::setprecision(6)
				<< static_cast<float>(p.x) << ", " << static_cast<float>(p.y)
				<< ", " << static_cast<float>(p.theta)
				<< ")";
			first = false;
		}
	}

	out << "};\n";
}

// prints V = {(linear, angular),(linear, angular),...}
void printVelocityVectorCpp(
	std::ostream& out,
	const std::string& label,
	const std::vector<std::vector<VelocityLayout>>& vels
) {
	out << label << " {";

	bool first = true;
	for (const auto& row : vels) {
		for (const auto& v : row) {
			if (!first) out << ",";
			out << "("
				<< std::fixed << std::setprecision(6)
				<< static_cast<float>(v.linear) << ", " << static_cast<float>(v.angular)
				<< ")";
			first = false;
		}
	}

	out << "};\n";
}

void printScalarSamplesDesmos(
	std::ostream& out,
	const std::vector<ScalarSample>& samples
) {
	printAgainstTime(out, "P = ", samples, &ScalarSample::position);
	printAgainstTime(out, "V = ", samples, &ScalarSample::velocity);
	printAgainstTime(out, "A = ", samples, &ScalarSample::accel);
}

// prints S = {{position, velocity, accel},{position, velocity, accel},...};
void printScalarSamplesCpp(
	std::ostream& out,
	const std::vector<ScalarSample>& samples
) {
	out << "S = {";
	for (size_t i = 0; i < samples.size(); ++i) {
		if (i != 0) out << ",";
		out << "{"
			<< std::fixed << std::setprecision(6)
			<< static_cast<float>(samples[i].position) << ", "
			<< static_cast<float>(samples[i].velocity) << ", "
			<< static_cast<float>(samples[i].accel)
			<< "}";
	}
	out << "};\n";
}

void printVelocitySamplesDesmos(
	std::ostream& out,
	const std::vector<VelocitySample>& samples
) {
	printAgainstTime(out, "V = ", samples, &VelocitySample::velocity);
	printAgainstTime(out, "A = ", samples, &VelocitySample::accel);
}

// prints S = {{velocity, accel},{velocity, accel},...};
void printVelocitySamplesCpp(
	std::ostream& out,
	const std::vector<VelocitySample>& samples
) {
	out << "S = {";
	for (size_t i = 0; i < samples.size(); ++i) {
		if (i != 0) out << ",";
		out << "{"
			<< std::fixed << std::setprecision(6)
			<< static_cast<float>(samples[i].velocity) << ", "
			<< static_cast<float>(samples[i].accel)
			<< "}";
	}
	out << "};\n";
}

void printScalarSamplesRust(
	std::ostream& out,
	const std::vector<ScalarSample>& samples
) {
	printMotionSamplesRust(out, samples);
}

void printVelocitySamplesRust(
	std::ostream& out,
	const std::vector<VelocitySample>& samples
) {
	printMotionSamplesRust(out, samples);
}

void printDriveSamplesRust(
	std::ostream& out,
	const std::vector<DriveSample>& samples
) {
	out << kRustHeader
	    << "#[derive(Clone, Copy, Debug, PartialEq)]\n"
	       "pub struct DriveSample {\n"
	       "    /// s\n"
	       "    pub time: f64,\n"
	       "    /// m/s, at the centre of the robot\n"
	       "    pub linear_velocity: f64,\n"
	       "    /// rad/s, counterclockwise positive\n"
	       "    pub angular_velocity: f64,\n"
	       "    /// m/s\n"
	       "    pub left_velocity: f64,\n"
	       "    /// m/s\n"
	       "    pub right_velocity: f64,\n"
	       "    /// m/s^2 that carry the left side to the next sample; 0 at the last\n"
	       "    pub left_accel: f64,\n"
	       "    /// m/s^2 that carry the right side to the next sample; 0 at the last\n"
	       "    pub right_accel: f64,\n"
	       "}\n"
	       "\n"
	       "pub static SAMPLES: &[DriveSample] = &[\n";
	for (const DriveSample& s : samples) {
		out << "    DriveSample { time: " << rustFloat(s.time)
		    << ", linear_velocity: " << rustFloat(s.linear)
		    << ", angular_velocity: " << rustFloat(s.angular)
		    << ", left_velocity: " << rustFloat(s.leftVelocity)
		    << ", right_velocity: " << rustFloat(s.rightVelocity)
		    << ", left_accel: " << rustFloat(s.leftAccel)
		    << ", right_accel: " << rustFloat(s.rightAccel) << " },\n";
	}
	out << "];\n";
}
}
