name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make all WARNINGS="-Wall -Wextra -Wshadow -Werror"
    - name: test
      run: make test WARNINGS="-Wall -Wextra -Wshadow -Werror"
    - name: run path example
      run: ./bin/main path --file examples/path-points.txt --max-vel 1.8885 --max-accel 4.1220 --track-width 0.2951
    - name: run path example without a mode
      run: ./bin/main --file examples/path-points.txt --max-vel 1.8885 --max-accel 4.1220 --track-width 0.2951
    - name: build examples
      run: make example WARNINGS="-Wall -Wextra -Wshadow -Werror"
    - name: run linear example
      run: ./bin/main linear --file examples/lift.txt --max-vel 1.2 --max-accel 3.0
    - name: run velocity example
      run: ./bin/main velocity --file examples/flywheel.txt --max-accel 800 --max-vel 450
