name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make all WARNINGS="-Wall -Wextra -Wshadow -Werror"
    - name: test
      run: make test WARNINGS="-Wall -Wextra -Wshadow -Werror"
    - name: run example
      run: ./bin/main --file examples/path-points.txt
